# Generated by Django 5.2.5 on 2025-09-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BestNews',
            fields=[
                ('Rank', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=500)),
                ('Link_To_Article', models.URLField(max_length=500)),
                ('Points', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Post_Time', models.CharField(max_length=100)),
                ('Scraped_Page_Link', models.URLField(max_length=500)),
            ],
        ),
    ]
